PYTHON=python3
VENV=venv
# Install dependencies from requirements.txt
install:
	$(PYTHON) -m venv $(VENV)
	pip install -r requirements.txt

deploy:
	python -m daphne -b 0.0.0.0 -p 8000 dataFreaks.asgi:application

startMat:
	python trajectoryFreaks/mat.py